# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'USA Sport Zone' do
   # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Parcel & Freight App
   pod 'SkyFloatingLabelTextField', '~> 3.0'
   pod 'IQKeyboardManagerSwift'
   pod 'Alamofire' , '~> 4.7'
   pod 'NVActivityIndicatorView' # loader
   pod 'Toast-Swift', '~> 5.0.1'
   pod 'Kingfisher'
   pod 'SCLAlertView'
   pod 'UITextField+Shake', '~> 1.2'
   pod 'ReachabilitySwift'
   pod 'DLRadioButton'
   pod 'IQDropDownTextField'
   pod 'SideMenu'
   pod 'lottie-ios'
   #pod 'AlamofireSwiftyJSON'
   pod 'SwiftSoup'
end
